import Head from "next/head";
import Image from "next/image";
import MainComponent from "../components/MainComponent";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainComponent></MainComponent>
    </div>
  );
}
